# Generated by Django 4.1.2 on 2023-09-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_images', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('Bicicletas', 'Bicicleta'), ('Bicileta de Montaña', 'Bicileta de Montaña'), ('Bicicleta Hibrida', 'Bicicleta Hibrida'), ('Bicicleta BMX', 'Bicicleta BMX')], max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('Sillines', 'Sillines'), ('Cadenas', 'Cadenas'), ('Ruedas', 'Ruedas'), ('Bomba de aire', 'Bomba de aire'), ('Manguitos', 'Manguitos'), ('Candado', 'Candado')], max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_h', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField()),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_list', models.ManyToManyField(to='tienda.product')),
            ],
        ),
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('billing_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('premium_user', models.BooleanField(default=False)),
                ('admin_user', models.BooleanField(default=False)),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_user'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_list', models.ManyToManyField(to='tienda.product')),
            ],
        ),
    ]
