# Generated by Django 4.1.2 on 2023-09-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_subcategories', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Bicicletas', 'Bicicleta'), ('Accesorios', 'Accesorios')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Sillines', 'Sillines'), ('Cadenas', 'Cadenas'), ('Ruedas', 'Ruedas'), ('Bomba de aire', 'Bomba de aire'), ('Manguitos', 'Manguitos'), ('Candado', 'Candado'), ('Bicicleta de Montaña', 'Bicicleta de Montaña'), ('Bicicleta Hibrida', 'Bicicleta Hibrida'), ('Bicicleta BMX', 'Bicicleta BMX')], max_length=100, null=True),
        ),
    ]
