# Generated by Django 4.1.2 on 2023-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categories_subcategories_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='id_product',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Bicicletas', 'Bicicletas'), ('Accesorios', 'Accesorios')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Montaña', 'Montaña'), ('BMX', 'BMX'), ('Urbano', 'Urbano'), ('Grava', 'Grava'), ('Electrica', 'Electrica'), ('Accesorios', 'Accesorios')], max_length=100, null=True),
        ),
    ]
